fieldLayouts:
  d089b582-dbe2-4a8a-9833-0c8d74c14eb2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 012ec432-1657-4941-8eac-3428efc0dd54
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6bde6d29-9e5a-4a8c-9d41-d8e5d12ec33d # Page Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba6a410c-648c-4cd0-9348-6fa098fc9b94
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5e136e6-160f-4093-91eb-52eb34f64558
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fa35bcb3-3708-420c-b074-15d36e91b1eb # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4331e8c-3798-4b7b-b854-4f24feef5463
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 49cbcc3a-1c11-4828-984d-7df28b6db7eb
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 3a32bed0-f47f-4af6-b970-7770b361e95a # Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
