fieldLayouts:
  2ec054f7-26b7-4cab-81c0-cd9d58154996:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 824b6bdc-741d-412d-8313-1bc4c47db534
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 223e7dac-c6de-46ba-9144-0ee4c62734c4 # Page Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 658a12cc-66b8-4af1-815d-3a0e4e7cc600
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8afe90dd-17af-457d-b51a-476ccdc2eafe
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 380a83b9-344d-415b-a3f4-8b389ef61717 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0e4d1aa-4c18-430e-bb0f-5af3443a7031
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 8ff733ec-f62e-4838-87d0-b3aa152e28d4
        userCondition: null
handle: default
hasTitleField: true
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
