color: null
fieldLayouts:
  87909c62-e82d-4f86-ab01-0a1de5f9f7cf:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: b852bf76-b8db-4acb-9a01-61fe22778bb1
        userCondition: null
handle: text
hasTitleField: false
icon: null
name: Text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
