baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: your-project-title
primary: true
siteGroup: 31abb75d-dc87-4ff3-a413-bb161bd3a59f # your-project-title
sortOrder: 1
