columnSuffix: null
contentColumnType: string
fieldGroup: bfe9a900-d516-42f7-8a87-a91c181779c0 # Common
handle: pageContent
instructions: null
name: 'Page Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagecontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
