columnSuffix: null
contentColumnType: string
handle: pageContent
instructions: null
name: 'Page Content'
searchable: false
settings:
  entryTypes:
    - adacfc6e-cbe6-4bc6-b486-3c04cfbd4b0b
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
