columnSuffix: null
handle: pageContent
instructions: null
name: 'Page Content'
searchable: true
settings:
  createButtonLabel: 'Add a block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - adacfc6e-cbe6-4bc6-b486-3c04cfbd4b0b # Text
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  siteSettings:
    __assoc__:
      -
        - 0eec63d1-8a33-4f6a-83a5-00c027db46dc # your-project-title
        -
          __assoc__:
            -
              - uriFormat
              - 'preview/block/{id}'
            -
              - template
              - previews/_block.twig
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
