columnSuffix: null
handle: postContent
instructions: null
name: 'Post Content'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: cdebb3ec-ae8f-4b56-ab25-7afbf135a0d3 # Post Content
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
