defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 253489f3-4e59-48ac-a725-d8592cb0ed1e # Page
handle: blockGuide
maxAuthors: 1
minAuthors: 1
name: 'Block Guide'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  0eec63d1-8a33-4f6a-83a5-00c027db46dc: # your-project-title
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: block-guide
type: single
