defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a41668f7-a432-4cc4-a09b-609538ea0125 # Homepage
handle: homepage
maxAuthors: 1
minAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  0eec63d1-8a33-4f6a-83a5-00c027db46dc: # your-project-title
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
