defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  33e725ff-6a81-4865-9ac0-079fac72c0cb: # your-project-title
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
