defaultPlacement: end
enableVersioning: true
entryTypes:
  - 253489f3-4e59-48ac-a725-d8592cb0ed1e # Page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0eec63d1-8a33-4f6a-83a5-00c027db46dc: # your-project-title
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: e821412c-15da-40bb-a6bb-6317be4eb4ab
type: structure
