name: Deploy

on:
  push:
    branches: [your-main-branch]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Pull repository into the current pipeline
      - name: Pull repository
        uses: actions/checkout@v4

      # Setup container with private SSH Key (used by rsync)
      - name: Load private SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # Use a specific version of Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      # Install PHP dependencies
      - name: Composer install
        run: composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

      # Install NPM dependencies
      - name: NPM install
        run: npm i --prefer-offline --no-audit --progress=false

      # Build assets
      - name: Build assets
        run: NODE_ENV=production npm run build

      # rsync
      - name: Deploy with rsync
        run: |
          rsync -v -a -z --delete --recursive --exclude={".babelrc",".browserslistrc",".dockerignore",".editorconfig",".env*",".eslintignore",".eslintrc",".git",".gitignore",".hygen.js",".nvmrc",".prettierrc",".prettierignore",".stylelintrc",".swcrc","/.cache/","/.composer/","/.config/","/.local/","/.npm/","/.github/","/.swc/","/bin/","/bower_components/","/cypress/","/docker/","/gulp/","/log/","/node_modules/","/resources/","/src/","/storage/logs/","_templates","/tmp/","/web/assets/","auth.json","babel.config.json","bower.json","buddy.yml","composer.json","composer.lock","cypress.json","docker-compose.yml","Dockerfile","env.sample","FauxTwigExtension.php","gsap-bonus.tgz","gulpfile.js","package.json","package-lock.json","public","README.md","tsconfig.json","vite.config.js","vite.config.mjs","yarn.lock"} -e "ssh -o StrictHostKeyChecking=no" ./ ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.SSH_DEPLOY_PATH }}

      # execute Craft commands on remote server
      - name: Execute SSH commands on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ vars.SSH_DEPLOY_PATH }}
            ln -s ${{ vars.SSH_DEPLOY_PATH }}/web ${{ vars.SSH_DEPLOY_PATH }}/public
            chmod a+x craft
            php craft db/backup
            php craft migrate/all
            php craft project-config/apply
            php craft invalidate-tags/template
            php craft blitz/cache/refresh

      # Pushover notification
      - name: Push Build Status Notifications
        if: ${{ always() }}
        uses: desiderati/github-action-pushover@v1
        with:
          job-status: ${{ job.status }}
          pushover-api-token: ${{ secrets.PUSHOVER_API_TOKEN }}
          pushover-user-key: ${{ vars.PUSHOVER_USER_KEY }}
