name: Deploy

on:
  push:
    branches: [main, dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Set environment
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi

  build-and-deploy:
    needs: setup
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.environment }}

    steps:
      # Display target environment
      - name: Show environment
        run: echo "Deploying to environment ${{ needs.setup.outputs.environment }}"

      # Pull repository into the current pipeline
      - name: Pull repository
        uses: actions/checkout@v4

      # Setup container with private SSH Key (used by rsync)
      - name: Load private SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # Use a specific version of Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      # Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Cache NPM dependencies
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install PHP dependencies
      - name: Composer install
        run: composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

      # Install NPM dependencies
      - name: NPM install
        run: npm i --prefer-offline --no-audit --progress=false

      # Build assets
      - name: Build assets
        run: NODE_ENV=production npm run build

      # rsync
      - name: Deploy with rsync
        run: |
          rsync -v -a -z \
          --delete \
          --recursive \
          --exclude=".babelrc" \
          --exclude=".browserslistrc" \
          --exclude=".dockerignore" \
          --exclude=".editorconfig" \
          --exclude=".env*" \
          --exclude=".eslintignore" \
          --exclude=".eslintrc" \
          --exclude=".git" \
          --exclude=".gitignore" \
          --exclude=".nvmrc" \
          --exclude=".prettierignore" \
          --exclude=".prettierrc" \
          --exclude=".stylelintrc" \
          --exclude="/.cache/" \
          --exclude="/.composer/" \
          --exclude="/.config/" \
          --exclude="/.github/" \
          --exclude="/.local/" \
          --exclude="/.npm/" \
          --exclude="/bin/" \
          --exclude="/cypress/" \
          --exclude="/docker/" \
          --exclude="/gulp/" \
          --exclude="/log/" \
          --exclude="/node_modules/" \
          --exclude="/resources/" \
          --exclude="/src/" \
          --exclude="/storage/logs/" \
          --exclude="/tmp/" \
          --exclude="/web/assets/" \
          --exclude="Dockerfile" \
          --exclude="FauxTwigExtension.php" \
          --exclude="README.md" \
          --exclude="auth.json" \
          --exclude="composer.json" \
          --exclude="composer.lock" \
          --exclude="cypress.json" \
          --exclude="docker-compose.yml" \
          --exclude="package-lock.json" \
          --exclude="package.json" \
          --exclude="plop-templates" \
          --exclude="plopfile.js" \
          --exclude="public" \
          --exclude="tsconfig.json" \
          --exclude="vite.config.js" \
          --exclude="vite.config.mjs" \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.SSH_DEPLOY_PATH }}

      # execute Craft commands on remote server
      - name: Execute SSH commands on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ vars.SSH_DEPLOY_PATH }}
            ln -s ${{ vars.SSH_DEPLOY_PATH }}/web ${{ vars.SSH_DEPLOY_PATH }}/public
            chmod a+x craft
            php craft db/backup
            php craft migrate/all
            php craft project-config/apply
            php craft invalidate-tags/template
            php craft blitz/cache/refresh

      # Pushover notification
      - name: Push Build Status Notifications
        if: ${{ always() }}
        uses: desiderati/github-action-pushover@v1
        with:
          job-status: ${{ job.status }}
          pushover-api-token: ${{ secrets.PUSHOVER_API_TOKEN }}
          pushover-user-key: ${{ vars.PUSHOVER_USER_KEY }}
